steps:
  # ============================================
  # PHASE 1: Setup & Prerequisites
  # ============================================
  
  # Schritt 1: APIs aktivieren (falls noch nicht aktiviert)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Aktiviere erforderliche APIs..."
        gcloud services enable cloudbuild.googleapis.com --project=$PROJECT_ID || true
        gcloud services enable run.googleapis.com --project=$PROJECT_ID || true
        gcloud services enable containerregistry.googleapis.com --project=$PROJECT_ID || true
        gcloud services enable storage.googleapis.com --project=$PROJECT_ID || true
        echo "APIs aktiviert"
    id: 'enable-apis'
  
  # Schritt 2: Cloud Storage Bucket prüfen/erstellen
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Prüfe Cloud Storage Bucket: gs://411832844870-anschreiben-data"
        
        # Prüfe ob Bucket existiert
        if gcloud storage buckets describe "gs://411832844870-anschreiben-data" --project=$PROJECT_ID &> /dev/null; then
          echo "✓ Bucket existiert bereits: gs://411832844870-anschreiben-data"
        else
          echo "Bucket existiert nicht. Erstelle Bucket..."
          gcloud storage buckets create "gs://411832844870-anschreiben-data" \
            --location="europe-west1" \
            --project=$PROJECT_ID
          
          if [ $? -eq 0 ]; then
            echo "✓ Bucket erfolgreich erstellt: gs://411832844870-anschreiben-data"
          else
            echo "⚠ Fehler beim Erstellen des Buckets (kann ignoriert werden, falls bereits vorhanden)"
          fi
        fi
    id: 'setup-cloud-storage'
    waitFor: ['enable-apis']
  
  # ============================================
  # PHASE 2: Code Quality & Tests
  # ============================================
  
  # Schritt 3: Dependencies installieren
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']
    id: 'install-dependencies'
    waitFor: ['setup-cloud-storage']
  
  # Schritt 4: TypeScript Type-Check
  - name: 'node:18'
    entrypoint: 'npx'
    args: ['tsc', '--noEmit']
    id: 'type-check'
    waitFor: ['install-dependencies']
  
  # Schritt 5: Lint-Check (optional, kann deaktiviert werden)
  # - name: 'node:18'
  #   entrypoint: 'npm'
  #   args: ['run', 'lint']
  #   id: 'lint-check'
  #   waitFor: ['type-check']
  
  # Schritt 6: Pre-Deployment E2E Tests (blockieren Deployment bei Fehlern)
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installiere Playwright..."
        npx playwright install --with-deps chromium
        
        echo "Führe E2E Tests gegen Production aus..."
        npm run test:e2e
    env:
      - 'TEST_BASE_URL=https://anschreiben-app-411832844870.europe-west1.run.app'
      - 'CI=true'
    id: 'pre-deploy-e2e-tests'
    waitFor: ['type-check']
  
  # ============================================
  # PHASE 3: Build & Push
  # ============================================
  
  # Schritt 7: Docker Image bauen
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Baue Docker Image..."
        docker build \
          -t gcr.io/$PROJECT_ID/anschreiben-app:$${SHORT_SHA:-$(date +%Y%m%d-%H%M%S)} \
          -t gcr.io/$PROJECT_ID/anschreiben-app:latest \
          .
        echo "✓ Image erfolgreich gebaut"
    id: 'build-image'
    waitFor: ['pre-deploy-e2e-tests']
  
  # Schritt 8: Docker Image zu Container Registry pushen
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        IMAGE_TAG=$${SHORT_SHA:-$(date +%Y%m%d-%H%M%S)}
        echo "Pushe Image zu Container Registry..."
        docker push gcr.io/$PROJECT_ID/anschreiben-app:$$IMAGE_TAG || echo "⚠ Fehler beim Pushen der Version, versuche latest..."
        docker push gcr.io/$PROJECT_ID/anschreiben-app:latest
        echo "✓ Image erfolgreich gepusht"
    id: 'push-image'
    waitFor: ['build-image']
  
  # ============================================
  # PHASE 4: Pre-Deployment Backup
  # ============================================
  
  # Schritt 9: Datenbank-Backup vor Deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        TIMESTAMP=$(date +%Y%m%d-%H%M%S)
        echo "Erstelle Datenbank-Backup vor Deployment..."
        curl -X POST "https://anschreiben-app-411832844870.europe-west1.run.app/api/admin/database/backup" \
          --max-time 30 \
          || echo "⚠ Backup-Endpoint nicht erreichbar (kann ignoriert werden)"
    id: 'pre-deploy-backup'
    waitFor: ['push-image']
  
  # ============================================
  # PHASE 5: Deployment
  # ============================================
  
  # Schritt 10: Deploy zu Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'anschreiben-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/anschreiben-app:latest'
      - '--region'
      - 'europe-west1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '2Gi'
      - '--cpu'
      - '2'
      - '--timeout'
      - '300'
      - '--max-instances'
      - '10'
      - '--set-env-vars'
      - 'GOOGLE_GENERATIVE_AI_API_KEY=${_GOOGLE_GENERATIVE_AI_API_KEY},GCS_BUCKET_NAME=411832844870-anschreiben-data'
      - '--project'
      - '$PROJECT_ID'
    id: 'deploy'
    waitFor: ['pre-deploy-backup']
  
  # ============================================
  # PHASE 6: Post-Deployment Verification
  # ============================================
  
  # Schritt 11: Service Status prüfen
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Prüfe Service Status..."
        DEPLOYED_SERVICE_URL=$$(gcloud run services describe anschreiben-app \
          --region=europe-west1 \
          --format='value(status.url)' \
          --project=$$PROJECT_ID)
        
        echo "Service URL: $$DEPLOYED_SERVICE_URL"
        echo "Warte 10 Sekunden auf Service-Bereitschaft..."
        sleep 10
        
        # Health Check
        echo "Führe Health Check durch..."
        curl -f "$$DEPLOYED_SERVICE_URL/api/admin/database/sync" --max-time 30 || echo "⚠ Health Check fehlgeschlagen"
    id: 'post-deploy-status-check'
    waitFor: ['deploy']
  
  # Schritt 12: Post-Deployment Smoke Tests
  - name: 'node:18'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Installiere Dependencies für Smoke Tests..."
        npm ci
        
        echo "Installiere Playwright..."
        npx playwright install --with-deps chromium
        
        echo "Führe Smoke Tests aus..."
        npm run test:smoke || echo "⚠ Smoke Tests fehlgeschlagen, aber Deployment abgeschlossen"
    env:
      - 'TEST_BASE_URL=https://anschreiben-app-411832844870.europe-west1.run.app'
      - 'CI=true'
    id: 'post-deploy-smoke-tests'
    waitFor: ['post-deploy-status-check']
  
  # Schritt 13: Finale Status-Ausgabe
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo ""
        echo "=========================================="
        echo "✓ Deployment erfolgreich abgeschlossen!"
        echo "=========================================="
        echo ""
        DEPLOYED_SERVICE_URL=$$(gcloud run services describe anschreiben-app \
          --region=europe-west1 \
          --format='value(status.url)' \
          --project=$$PROJECT_ID)
        
        echo "Service URL: $$DEPLOYED_SERVICE_URL"
        echo "Production URL: https://anschreiben-app-411832844870.europe-west1.run.app"
        echo ""
        echo "Nächste Schritte:"
        echo "1. Service testen: curl $$DEPLOYED_SERVICE_URL/api/admin/database/sync"
        echo "2. Admin-Panel öffnen: $$DEPLOYED_SERVICE_URL/admin/database"
        echo "3. Logs prüfen: gcloud run services logs read anschreiben-app --region=europe-west1"
        echo ""
    id: 'final-status'
    waitFor: ['post-deploy-smoke-tests']

images:
  - 'gcr.io/$PROJECT_ID/anschreiben-app:latest'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  # timeout: '1800s'  # 30 minutes max - wird automatisch von Cloud Build gesetzt

# Store test artifacts
artifacts:
  objects:
    location: 'gs://${PROJECT_ID}-build-artifacts'
    paths:
      - 'test-results/**'
      - 'playwright-report/**'
